# site settings
title: Darren J. Scott
subtitle: #Physicist (particle theory)
email:
description: TEST
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://darrenjamesscott.com" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country: United Kingdom
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Envelope: test@test.com # For emails - the Envelope tag is important so it puts the right symbol at the bottom
  GitHub: https://github.com/darrenjscott
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
